#!/bin/bash

# Переключение на ветку "dev"
git checkout dev

# Подтверждение изменений и создание ревизии
git commit -am "Перенос ревизии в prd"

# Переключение на ветку "prd"
git checkout prd

# Слияние ветки "dev" с веткой "prd"
git merge dev

# Создание тэга с текущим временем в формате yyyy/MM/dd/HH/mm/ss
tag=$(date +'%Y%m%d_%H%M%S')

# Установка тэга на последнюю ревизию в ветке "prd"
git tag $tag

# Подталкивание изменений в удаленный репозиторий
git push origin prd --tags
